-- MySQL Script generated by MySQL Workbench
-- Wed Jan 24 17:21:09 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Horariosdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Horariosdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Horariosdb` DEFAULT CHARACTER SET utf8 ;
USE `Horariosdb` ;

-- -----------------------------------------------------
-- Table `Horariosdb`.`Profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Horariosdb`.`Profesor` (
  `Cedula` VARCHAR(30) NOT NULL,
  `Nombre` VARCHAR(100) NOT NULL,
  `Telefono` VARCHAR(20) NOT NULL,
  `Correo` VARCHAR(45) NOT NULL,
  `Estado` INT NOT NULL,
  PRIMARY KEY (`Cedula`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
